import type { Category } from './types';

export const PREDEFINED_CATEGORIES: Omit<Category, 'id'>[] = [
  { name: 'Groceries' },
  { name: 'Rent' },
  { name: 'Utilities' },
  { name: 'Transport' },
  { name: 'Dining Out' },
  { name: 'Entertainment' },
  { name: 'Shopping' },
  { name: 'Other' },
];

export const CURRENCIES: { code: string; name: string; symbol: string }[] = [
  { code: 'USD', name: 'United States Dollar', symbol: '$' },
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
  { code: 'GBP', name: 'British Pound Sterling', symbol: '£' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺' },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$' },
];

export const COUNTRY_CODES: { name: string; dial_code: string; code: string }[] = [
    { name: 'United States', dial_code: '+1', code: 'US' },
    { name: 'India', dial_code: '+91', code: 'IN' },
    { name: 'Sweden', dial_code: '+46', code: 'SE' },
    { name: 'United Kingdom', dial_code: '+44', code: 'GB' },
    { name: 'Afghanistan', dial_code: '+93', code: 'AF' },
    { name: 'Albania', dial_code: '+355', code: 'AL' },
    { name: 'Algeria', dial_code: '+213', code: 'DZ' },
    { name: 'American Samoa', dial_code: '+1684', code: 'AS' },
    { name: 'Andorra', dial_code: '+376', code: 'AD' },
    { name: 'Angola', dial_code: '+244', code: 'AO' },
    { name: 'Argentina', dial_code: '+54', code: 'AR' },
    { name: 'Australia', dial_code: '+61', code: 'AU' },
    { name: 'Austria', dial_code: '+43', code: 'AT' },
    { name: 'Brazil', dial_code: '+55', code: 'BR' },
    { name: 'Canada', dial_code: '+1', code: 'CA' },
    { name: 'China', dial_code: '+86', code: 'CN' },
    { name: 'Egypt', dial_code: '+20', code: 'EG' },
    { name: 'France', dial_code: '+33', code: 'FR' },
    { name: 'Germany', dial_code: '+49', code: 'DE' },
    { name: 'Indonesia', dial_code: '+62', code: 'ID' },
    { name: 'Italy', dial_code: '+39', code: 'IT' },
    { name: 'Japan', dial_code: '+81', code: 'JP' },
    { name: 'Mexico', dial_code: '+52', code: 'MX' },
    { name: 'Netherlands', dial_code: '+31', code: 'NL' },
    { name: 'New Zealand', dial_code: '+64', code: 'NZ' },
    { name: 'Nigeria', dial_code: '+234', code: 'NG' },
    { name: 'Russia', dial_code: '+7', code: 'RU' },
    { name: 'Saudi Arabia', dial_code: '+966', code: 'SA' },
    { name: 'South Africa', dial_code: '+27', code: 'ZA' },
    { name: 'South Korea', dial_code: '+82', code: 'KR' },
    { name: 'Spain', dial_code: '+34', code: 'ES' },
    { name: 'Switzerland', dial_code: '+41', code: 'CH' },
    { name: 'Turkey', dial_code: '+90', code: 'TR' },
    { name: 'United Arab Emirates', dial_code: '+971', code: 'AE' },
];
